#!/bin/bash
# Sriptloader 0.2 by paskalito - 2013-02-07

# Relativer Pfad zum Ordner wo die zu Kopierenden Daten liegen.
PATHTODATA=/data

# Relativer Pfad zum Ordner wo die Auszuführenden Scripts Liegen.
PATHTOSCRIPTDIRECOTRY=/scripts

# Kriterien (find) nach denen die Scripts ausgesucht werden.
FILTER="run.*"

# Code um die Systemsprache zu bestimmen
LANGUAGECODE=`defaults read .GlobalPreferences AppleLanguages | tr -d [:space:] | cut -c2-3`
echo Sprache ist = $LANGUAGECODE

# ------------------------- >> LDAP Config Start << -------------------------
# With this Set Up you can Acess the Variable $USERISINLDAPGROUP which tells you if the current user is in a certain LDAP Group or not.


# Here you can define the shortname for the user (must be a variable!), and it has to equal the sAMAccountName in the LDAP Directory, if authenticate the User with ldap, it will Automatically equal the Systems $USER Variabel, this is why that is the default value.
USERSSAMACCOUNTNAME=$USER

LDAPSERVERIP=
# That user must have the rights to search the directory. (In Genreal that user dont have to be in ANY group (Except in the OU))
GENERICLDAPUSER=
GENERICLDAPUSERPASSWORD=
# This must be a String wehre every user you might target is in. (best to just define the Organisation Unit (ou), and Domain Controller (dc)) > Example = ou=Users,dc=mydomain,dc=com
LDAPSEARCHSTRING=


# ------------------------- >> LDAP Config END << -------------------------

#Code um Vor und Nachname zu bestimmen
PRENAME=`dscl . -read ~ RealName | tail -1 | cut -d " " -f2`
SURENAME=`dscl . -read ~ RealName | tail -1 | cut -d " " -f3`
echo Prename = $PRENAME
echo Surname = $SURNAME

LOWERCASEPRENAME=`dscl . -read ~ RealName | tail -1 | cut -d " " -f2 | tr '[:upper:]' '[:lower:]'`
LOWERCASESURENAME=`dscl . -read ~ RealName | tail -1 | cut -d " " -f3 | tr '[:upper:]' '[:lower:]'`
echo Prename-lowercase = $LOWERCASEPRENAME
echo Surname-lowercase = $LOWERCASESURNAME

# Extract Coputer UUID (Output will look something like this: 59F77AD6-103F-5D34-BA83-2366512989FA)
UUID=`/usr/sbin/system_profiler SPHardwareDataType Hardware: | grep UUID: | awk '{print $3}'`
echo UUID of current Computer = $UUID

STARLINE="***************************"
DOTLINE="---------------------------"


echo "$STARLINE"
echo Config-File Geladen
echo "$STARLINE"